export default [
  {
    "id": "iirx7a",
    "author": "GoldenJoel",
    "created_utc": 1598705746.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iirx7a",
    "num_comments": 144,
    "over_18": false,
    "permalink": "/r/videos/comments/iirx7a/jos\u00e9_\u00e1lvarez_takes_a_105_mph_line_drive_to_the/",
    "score": 1713,
    "spoiler": false,
    "stickied": false,
    "title": "Jos\u00e9 \u00c1lvarez takes a 105 mph line drive to the nuts, a breakdown",
    "upvote_ratio": 0.94,
    "url": "https://www.youtube.com/watch?v=dNa57aJQR9k"
  },
  {
    "id": "iiszx2",
    "author": "bkdrex",
    "created_utc": 1598710233.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiszx2",
    "num_comments": 66,
    "over_18": false,
    "permalink": "/r/videos/comments/iiszx2/when_you_hear_marc_rebillet_for_the_first_time/",
    "score": 1229,
    "spoiler": false,
    "stickied": false,
    "title": "When You Hear Marc Rebillet For The First Time",
    "upvote_ratio": 0.87,
    "url": "https://www.youtube.com/watch?v=z4aaHsXC7sI"
  },
  {
    "id": "iikp2y",
    "author": "SaladinsSaladbar",
    "created_utc": 1598668240.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iikp2y",
    "num_comments": 511,
    "over_18": false,
    "permalink": "/r/videos/comments/iikp2y/chadwick_bosemans_howard_university_2018/",
    "score": 34732,
    "spoiler": false,
    "stickied": false,
    "title": "Chadwick Boseman's Howard University 2018 Commencement Speech. RIP to a magnificent man.",
    "upvote_ratio": 0.84,
    "url": "https://www.youtube.com/watch?v=RIHZypMyQ2s"
  },
  {
    "id": "iit6yf",
    "author": "dustin1776",
    "created_utc": 1598710995.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iit6yf",
    "num_comments": 127,
    "over_18": false,
    "permalink": "/r/videos/comments/iit6yf/harry_connick_jr_slyly_added_an_extra_beat_to_his/",
    "score": 527,
    "spoiler": false,
    "stickied": false,
    "title": "Harry Connick, Jr slyly added an extra beat to his solo so that the audience was clapping on the appropriate 2nd and 4th beats.",
    "upvote_ratio": 0.87,
    "url": "https://www.youtube.com/watch?v=UinRq_29jPk"
  },
  {
    "id": "iih7qw",
    "author": "Ahliiee",
    "created_utc": 1598654400.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iih7qw",
    "num_comments": 758,
    "over_18": false,
    "permalink": "/r/videos/comments/iih7qw/my_brother_sharing_his_weightloss_journey_230lbs/",
    "score": 15501,
    "spoiler": false,
    "stickied": false,
    "title": "My brother sharing his weight-loss journey (-230lbs), for anyone looking to be inspired, anything is possible if you want it bad enough!",
    "upvote_ratio": 0.88,
    "url": "https://youtu.be/7hPV21Ofrb4"
  },
  {
    "id": "iiqfjx",
    "author": "R_Hugh_High",
    "created_utc": 1598698061.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiqfjx",
    "num_comments": 143,
    "over_18": false,
    "permalink": "/r/videos/comments/iiqfjx/it_blows_my_mind_that_weather_reporters_are_still/",
    "score": 390,
    "spoiler": false,
    "stickied": false,
    "title": "It blows my mind that weather reporters are still sent to broadcast Hurricanes live like this",
    "upvote_ratio": 0.89,
    "url": "https://youtu.be/JyRfTC6ErVs"
  },
  {
    "id": "iitect",
    "author": "hehyih",
    "created_utc": 1598711772.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iitect",
    "num_comments": 25,
    "over_18": false,
    "permalink": "/r/videos/comments/iitect/i_performed_all_the_characters_parts_to_one_day/",
    "score": 113,
    "spoiler": false,
    "stickied": false,
    "title": "I performed all the characters parts to \"One Day More\" from Les Mis\u00e9rables",
    "upvote_ratio": 0.78,
    "url": "https://youtu.be/nDGnxNAY48c"
  },
  {
    "id": "iir1kg",
    "author": "fprintf",
    "created_utc": 1598701445.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iir1kg",
    "num_comments": 9,
    "over_18": false,
    "permalink": "/r/videos/comments/iir1kg/60_seconds_of_stella_leaf_jumps_autumn_is_coming/",
    "score": 162,
    "spoiler": false,
    "stickied": false,
    "title": "60 seconds of Stella leaf jumps (Autumn is coming!)",
    "upvote_ratio": 0.88,
    "url": "https://youtu.be/D6S_TMd7Jkw"
  },
  {
    "id": "iiqu5s",
    "author": "tyler123418",
    "created_utc": 1598700339.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiqu5s",
    "num_comments": 55,
    "over_18": false,
    "permalink": "/r/videos/comments/iiqu5s/tobey_maguire_talks_about_spiderman_4_four_days/",
    "score": 154,
    "spoiler": false,
    "stickied": false,
    "title": "Tobey Maguire Talks about Spider-Man 4- Four Days Before It's Cancelled",
    "upvote_ratio": 0.84,
    "url": "https://www.youtube.com/watch?v=71opq7TIg4Y"
  },
  {
    "id": "iit9uu",
    "author": "LongWater2030",
    "created_utc": 1598711298.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iit9uu",
    "num_comments": 15,
    "over_18": false,
    "permalink": "/r/videos/comments/iit9uu/the_guy_who_doesnt_know_when_to_come_in_on_the/",
    "score": 86,
    "spoiler": false,
    "stickied": false,
    "title": "The Guy Who Doesn't Know When to Come in on the Beat",
    "upvote_ratio": 0.74,
    "url": "https://www.youtube.com/watch?v=m9NSnTxs27c"
  },
  {
    "id": "iim3zj",
    "author": "CCPbuttboy",
    "created_utc": 1598674359.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iim3zj",
    "num_comments": 104,
    "over_18": false,
    "permalink": "/r/videos/comments/iim3zj/a_tour_of_the_palo_verde_nuclear_plant_in_arizona/",
    "score": 411,
    "spoiler": false,
    "stickied": false,
    "title": "A tour of the Palo Verde Nuclear plant in Arizona, the largest power plant in the US which reuses wastewater, makes up 1% of all US energy and powers 4,000,000 homes with carbon-free energy.",
    "upvote_ratio": 0.92,
    "url": "https://www.youtube.com/watch?v=_DAW8XypU5Q"
  },
  {
    "id": "iiv2ef",
    "author": "FresnoBob-9000",
    "created_utc": 1598717545.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiv2ef",
    "num_comments": 9,
    "over_18": false,
    "permalink": "/r/videos/comments/iiv2ef/no_sir_i_dont_like_it/",
    "score": 43,
    "spoiler": false,
    "stickied": false,
    "title": "No Sir I Don\u2019t Like It",
    "upvote_ratio": 0.75,
    "url": "https://m.youtube.com/watch?v=dQ3acvz5LfI&fbclid=IwAR2KB4-ugyrqyWdV7viec8dc4U3E55AplNFdupr5ncgOEQPEdv3EhniXpcc"
  },
  {
    "id": "ii4xo8",
    "author": "junn0",
    "created_utc": 1598612011.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_ii4xo8",
    "num_comments": 1125,
    "over_18": false,
    "permalink": "/r/videos/comments/ii4xo8/karens_but_with_zombie_noises/",
    "score": 27087,
    "spoiler": false,
    "stickied": false,
    "title": "Karens But With Zombie Noises",
    "upvote_ratio": 0.89,
    "url": "https://www.youtube.com/watch?v=MCAoMPKWIy0"
  },
  {
    "id": "iip76w",
    "author": "fonedork",
    "created_utc": 1598690846.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iip76w",
    "num_comments": 16,
    "over_18": false,
    "permalink": "/r/videos/comments/iip76w/absurdly_good_actingmonologue_by_jeanclaude_van/",
    "score": 101,
    "spoiler": false,
    "stickied": false,
    "title": "Absurdly good acting/monologue by Jean-Claude Van Damme in the movie JCVD",
    "upvote_ratio": 0.82,
    "url": "https://m.youtube.com/watch?v=vMvdGC2FIEU"
  },
  {
    "id": "iixiyn",
    "author": "dutugemunu",
    "created_utc": 1598725776.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iixiyn",
    "num_comments": 3,
    "over_18": false,
    "permalink": "/r/videos/comments/iixiyn/a_tug_of_war_with_mako_shark_over_a_tuna/",
    "score": 16,
    "spoiler": false,
    "stickied": false,
    "title": "A tug of war with Mako Shark over a tuna!",
    "upvote_ratio": 0.84,
    "url": "https://www.youtube.com/watch?v=tKEVQjAIp-o&t=2s"
  },
  {
    "id": "iitq9i",
    "author": "FishCake9T4",
    "created_utc": 1598713020.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iitq9i",
    "num_comments": 5,
    "over_18": false,
    "permalink": "/r/videos/comments/iitq9i/chadwick_boseman_breaks_down_when_talking_about_2/",
    "score": 29,
    "spoiler": false,
    "stickied": false,
    "title": "Chadwick Boseman breaks down when talking about 2 kids with cancer who were Black Panther fans.",
    "upvote_ratio": 0.62,
    "url": "https://www.youtube.com/watch?v=6J-D86wfxiEaaa"
  },
  {
    "id": "iif6pe",
    "author": "alex_dlc",
    "created_utc": 1598647603.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iif6pe",
    "num_comments": 110,
    "over_18": false,
    "permalink": "/r/videos/comments/iif6pe/lemmino_extraordinary_until_proven_otherwise/",
    "score": 757,
    "spoiler": false,
    "stickied": false,
    "title": "LEMMiNO - Extraordinary Until Proven Otherwise",
    "upvote_ratio": 0.9,
    "url": "https://www.youtube.com/watch?v=SpeSpA3e56A"
  },
  {
    "id": "iimqed",
    "author": "clerksfanboy",
    "created_utc": 1598677314.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iimqed",
    "num_comments": 30,
    "over_18": false,
    "permalink": "/r/videos/comments/iimqed/something_terribly_offensive_animation/",
    "score": 148,
    "spoiler": false,
    "stickied": false,
    "title": "Something Terribly Offensive (animation)",
    "upvote_ratio": 0.77,
    "url": "https://www.youtube.com/watch?v=EkDOuRAwrYE"
  },
  {
    "id": "iij6qk",
    "author": "Hjaaal",
    "created_utc": 1598661961.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iij6qk",
    "num_comments": 122,
    "over_18": false,
    "permalink": "/r/videos/comments/iij6qk/a_nintendo_training_video_from_1991_teaching/",
    "score": 314,
    "spoiler": false,
    "stickied": false,
    "title": "A Nintendo training video from 1991 teaching retail workers how to handle customers with defective Nintendo products.",
    "upvote_ratio": 0.9,
    "url": "https://www.youtube.com/watch?v=WYjgHLFZMa0"
  },
  {
    "id": "iiww3h",
    "author": "dustin1776",
    "created_utc": 1598723678.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiww3h",
    "num_comments": 5,
    "over_18": false,
    "permalink": "/r/videos/comments/iiww3h/the_sound_of_the_glass_armonica_invented_by/",
    "score": 15,
    "spoiler": false,
    "stickied": false,
    "title": "The sound of the glass armonica, invented by Benjamin Franklin",
    "upvote_ratio": 0.8,
    "url": "https://m.youtube.com/watch?feature=emb_title&v=BdtLK9pAh5k"
  },
  {
    "id": "iiobk4",
    "author": "NaiadoftheSea",
    "created_utc": 1598685582.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiobk4",
    "num_comments": 9,
    "over_18": false,
    "permalink": "/r/videos/comments/iiobk4/a_series_of_fans_thank_chadwick_boseman_for_his/",
    "score": 89,
    "spoiler": false,
    "stickied": false,
    "title": "A series of fans thank Chadwick Boseman for his work and share what Black Panther means to them.",
    "upvote_ratio": 0.64,
    "url": "https://www.youtube.com/watch?v=expKmfdoo28"
  },
  {
    "id": "ii1fal",
    "author": "Tyropillar",
    "created_utc": 1598593050.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_ii1fal",
    "num_comments": 1433,
    "over_18": false,
    "permalink": "/r/videos/comments/ii1fal/4year_old_girl_found_drifting_off_the_coast_on_an/",
    "score": 22425,
    "spoiler": false,
    "stickied": false,
    "title": "4-year old girl found drifting off the coast on an inflatable unicorn.",
    "upvote_ratio": 0.95,
    "url": "https://twitter.com/rexchapman/status/1299033945154236426?s=21"
  },
  {
    "id": "iiwht2",
    "author": "_DrSpliff",
    "created_utc": 1598722381.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiwht2",
    "num_comments": 10,
    "over_18": false,
    "permalink": "/r/videos/comments/iiwht2/soviet_lollipop/",
    "score": 16,
    "spoiler": false,
    "stickied": false,
    "title": "Soviet Lollipop",
    "upvote_ratio": 0.76,
    "url": "https://www.youtube.com/watch?v=yzQ755X-jKw"
  },
  {
    "id": "iiwrdn",
    "author": "SuperNerd6527",
    "created_utc": 1598723252.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiwrdn",
    "num_comments": 4,
    "over_18": false,
    "permalink": "/r/videos/comments/iiwrdn/rob_lowe_goes_nuts/",
    "score": 12,
    "spoiler": false,
    "stickied": false,
    "title": "Rob Lowe Goes Nuts",
    "upvote_ratio": 0.72,
    "url": "https://www.youtube.com/watch?v=gJmT7jsfENo"
  },
  {
    "id": "iiswyu",
    "author": "spicymemeball",
    "created_utc": 1598709910.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiswyu",
    "num_comments": 20,
    "over_18": false,
    "permalink": "/r/videos/comments/iiswyu/dad_invented_ass_wiping_robot/",
    "score": 20,
    "spoiler": false,
    "stickied": false,
    "title": "Dad Invented Ass Wiping Robot",
    "upvote_ratio": 0.63,
    "url": "https://youtu.be/ZsyCAVv5IUI"
  },
  {
    "id": "iixpcr",
    "author": "GabrielLogan989",
    "created_utc": 1598726390.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iixpcr",
    "num_comments": 1,
    "over_18": false,
    "permalink": "/r/videos/comments/iixpcr/video_game_bathrooms_are_tight/",
    "score": 8,
    "spoiler": false,
    "stickied": false,
    "title": "Video game bathrooms are tight!",
    "upvote_ratio": 0.83,
    "url": "https://www.youtube.com/watch?v=fAD-bBKA6Ag"
  },
  {
    "id": "iin2tz",
    "author": "aKleverMan",
    "created_utc": 1598679051.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iin2tz",
    "num_comments": 13,
    "over_18": false,
    "permalink": "/r/videos/comments/iin2tz/gecko_on_a_washing_machine/",
    "score": 82,
    "spoiler": false,
    "stickied": false,
    "title": "Gecko on a washing machine",
    "upvote_ratio": 0.75,
    "url": "https://youtu.be/q20bDQ6ioKA"
  },
  {
    "id": "ii4dtl",
    "author": "Sikkas",
    "created_utc": 1598609149.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_ii4dtl",
    "num_comments": 197,
    "over_18": false,
    "permalink": "/r/videos/comments/ii4dtl/dave_chappelles_showing_reversed_roles_seemed_to/",
    "score": 2600,
    "spoiler": false,
    "stickied": false,
    "title": "Dave Chappelle's showing reversed roles seemed to be pretty accurate",
    "upvote_ratio": 0.89,
    "url": "https://www.youtube.com/watch?v=HeOVbeh2yr0"
  },
  {
    "id": "iiushm",
    "author": "slappingwatermelons",
    "created_utc": 1598716658.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiushm",
    "num_comments": 5,
    "over_18": false,
    "permalink": "/r/videos/comments/iiushm/why_the_world_only_has_two_words_for_tea/",
    "score": 10,
    "spoiler": false,
    "stickied": false,
    "title": "Why the World Only Has Two Words for Tea",
    "upvote_ratio": 0.67,
    "url": "https://www.youtube.com/watch?v=wzgvQLpoTbw"
  },
  {
    "id": "iiy5dz",
    "author": "Holes741",
    "created_utc": 1598727904.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiy5dz",
    "num_comments": 0,
    "over_18": false,
    "permalink": "/r/videos/comments/iiy5dz/when_your_professor_says_to_reply_to_at_least/",
    "score": 5,
    "spoiler": false,
    "stickied": false,
    "title": "When Your Professor Says to Reply to at Least Three Posts on the Discussion Board",
    "upvote_ratio": 1.0,
    "url": "https://www.youtube.com/watch?v=OvRPBCg8A2g"
  },
  {
    "id": "iiuq2j",
    "author": "eraldopontopdf",
    "created_utc": 1598716425.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiuq2j",
    "num_comments": 11,
    "over_18": false,
    "permalink": "/r/videos/comments/iiuq2j/the_smoothest_guitar_switch_ever/",
    "score": 6,
    "spoiler": false,
    "stickied": false,
    "title": "The smoothest guitar switch ever!",
    "upvote_ratio": 0.54,
    "url": "https://www.youtube.com/watch?v=JIFdMbhCa94"
  },
  {
    "id": "ii8b8d",
    "author": "Killcraft69",
    "created_utc": 1598625848.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_ii8b8d",
    "num_comments": 52,
    "over_18": false,
    "permalink": "/r/videos/comments/ii8b8d/chris_jack_secret_weakness/",
    "score": 751,
    "spoiler": false,
    "stickied": false,
    "title": "Chris & Jack | Secret Weakness",
    "upvote_ratio": 0.93,
    "url": "https://www.youtube.com/watch?v=mYEfWg9sWCM"
  },
  {
    "id": "iiy22p",
    "author": "GabrielLogan989",
    "created_utc": 1598727605.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiy22p",
    "num_comments": 0,
    "over_18": false,
    "permalink": "/r/videos/comments/iiy22p/i_know_tank_controls_are_terrible_but_i_still/",
    "score": 3,
    "spoiler": false,
    "stickied": false,
    "title": "I know tank controls are terrible, but I still miss that awkward camera in old horror survival games",
    "upvote_ratio": 0.8,
    "url": "https://www.youtube.com/watch?v=BLjKr1AEMnU"
  },
  {
    "id": "iik2ef",
    "author": "MrXhin",
    "created_utc": 1598665627.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iik2ef",
    "num_comments": 107,
    "over_18": false,
    "permalink": "/r/videos/comments/iik2ef/skydrive_performs_its_first_piloted_flight/",
    "score": 85,
    "spoiler": false,
    "stickied": false,
    "title": "SkyDrive performs its first piloted flight demonstration for the public.",
    "upvote_ratio": 0.86,
    "url": "https://youtu.be/4Yc2L5koWZY"
  },
  {
    "id": "iiw52t",
    "author": "TravestyAU",
    "created_utc": 1598721212.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiw52t",
    "num_comments": 6,
    "over_18": false,
    "permalink": "/r/videos/comments/iiw52t/after_2_years_away_from_youtube_and_content/",
    "score": 6,
    "spoiler": false,
    "stickied": false,
    "title": "After 2 years away from Youtube and content creation, SeaNanners returns (\"What Happened to SeaNanners? Why I Left the Internet\")",
    "upvote_ratio": 0.56,
    "url": "https://www.youtube.com/watch?v=LGEtE5ICTIM"
  },
  {
    "id": "iix9zf",
    "author": "e1ioan",
    "created_utc": 1598724951.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iix9zf",
    "num_comments": 1,
    "over_18": false,
    "permalink": "/r/videos/comments/iix9zf/old_song_we_use_to_sing_while_in_romanian_army_in/",
    "score": 5,
    "spoiler": false,
    "stickied": false,
    "title": "Old song we use to sing while in Romanian army. In the video the, Romanian army was crossing Danube, in the Romanian war of independence.",
    "upvote_ratio": 0.86,
    "url": "https://www.youtube.com/watch?v=eVxn61oITmQ"
  },
  {
    "id": "iit2ub",
    "author": "Hologramtrey",
    "created_utc": 1598710566.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iit2ub",
    "num_comments": 30,
    "over_18": false,
    "permalink": "/r/videos/comments/iit2ub/road_rage_driver_to_meill_fing_kill_you_nword_f/",
    "score": 5,
    "spoiler": false,
    "stickied": false,
    "title": "Road rage driver to me:\u201dI\u2019ll F-ing kill you N-word, F you, you F-ing f*gg*t\" (hopefully he finds the help and guidance one needs to overcome such an attitude)",
    "upvote_ratio": 0.53,
    "url": "https://youtu.be/gNJQiqBvMTM"
  },
  {
    "id": "iiboqp",
    "author": "schnorkel",
    "created_utc": 1598636564.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiboqp",
    "num_comments": 65,
    "over_18": false,
    "permalink": "/r/videos/comments/iiboqp/clever_humpback_whale_pops_up_for_an_expensive/",
    "score": 351,
    "spoiler": false,
    "stickied": false,
    "title": "Clever Humpback Whale Pops Up for an Expensive Snack",
    "upvote_ratio": 0.9,
    "url": "https://www.youtube.com/watch?v=lvGCF-K8SiQ"
  },
  {
    "id": "iinp1o",
    "author": "AndalusianGod",
    "created_utc": 1598682314.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iinp1o",
    "num_comments": 15,
    "over_18": false,
    "permalink": "/r/videos/comments/iinp1o/can_you_play_wonderwall/",
    "score": 30,
    "spoiler": false,
    "stickied": false,
    "title": "Can you play \"Wonderwall\" ?",
    "upvote_ratio": 0.7,
    "url": "https://www.youtube.com/watch?v=oOMACQIa9zI"
  },
  {
    "id": "iinhvh",
    "author": "pikachu_jade_no",
    "created_utc": 1598681265.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iinhvh",
    "num_comments": 9,
    "over_18": false,
    "permalink": "/r/videos/comments/iinhvh/found_the_full_version_and_its_has_so_many/",
    "score": 30,
    "spoiler": false,
    "stickied": false,
    "title": "Found the full version and its has so many potential meme templates",
    "upvote_ratio": 0.65,
    "url": "https://www.youtube.com/watch?v=vOGhAV-84iI"
  },
  {
    "id": "ii8x70",
    "author": "snowcone_wars",
    "created_utc": 1598627889.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_ii8x70",
    "num_comments": 72,
    "over_18": false,
    "permalink": "/r/videos/comments/ii8x70/internet_comment_etiquette_the_passion_of_the/",
    "score": 433,
    "spoiler": false,
    "stickied": false,
    "title": "Internet Comment Etiquette: \"The Passion of the Karen\"",
    "upvote_ratio": 0.81,
    "url": "https://www.youtube.com/watch?v=ju_5uD1eRZQ"
  },
  {
    "id": "iix9jd",
    "author": "ArminoKink",
    "created_utc": 1598724907.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iix9jd",
    "num_comments": 2,
    "over_18": false,
    "permalink": "/r/videos/comments/iix9jd/swedish_law_enforcement_in_new_york_city/",
    "score": 5,
    "spoiler": false,
    "stickied": false,
    "title": "Swedish Law Enforcement In New York City...",
    "upvote_ratio": 0.65,
    "url": "https://youtu.be/izdfnHBMwSs"
  },
  {
    "id": "iic0bx",
    "author": "DickTicker",
    "created_utc": 1598637557.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iic0bx",
    "num_comments": 38,
    "over_18": false,
    "permalink": "/r/videos/comments/iic0bx/the_other_guys_who_didnt_join_the_fellowship_in/",
    "score": 249,
    "spoiler": false,
    "stickied": false,
    "title": "The other guys who didn\u2019t join the fellowship in the lord of the rings",
    "upvote_ratio": 0.73,
    "url": "https://youtu.be/ghVAR6eOoHI"
  },
  {
    "id": "iis661",
    "author": "iza9",
    "created_utc": 1598706832.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iis661",
    "num_comments": 0,
    "over_18": false,
    "permalink": "/r/videos/comments/iis661/the_book_of_enoch_explained/",
    "score": 8,
    "spoiler": false,
    "stickied": false,
    "title": "The Book of Enoch Explained",
    "upvote_ratio": 0.79,
    "url": "https://www.youtube.com/watch?v=FsVQnspOkkY&feature=emb_title"
  },
  {
    "id": "iip3ob",
    "author": "withoutyousg",
    "created_utc": 1598690241.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iip3ob",
    "num_comments": 0,
    "over_18": false,
    "permalink": "/r/videos/comments/iip3ob/cj_gets_busted_by_spongebob/",
    "score": 13,
    "spoiler": false,
    "stickied": false,
    "title": "CJ gets busted by SpongeBob",
    "upvote_ratio": 0.64,
    "url": "https://www.youtube.com/watch?v=FQvuTmI8l4s"
  },
  {
    "id": "iil619",
    "author": "blackdynomitesnewbag",
    "created_utc": 1598670209.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iil619",
    "num_comments": 13,
    "over_18": false,
    "permalink": "/r/videos/comments/iil619/chadwick_boseman_on_snl_black_jeopardy/",
    "score": 39,
    "spoiler": false,
    "stickied": false,
    "title": "Chadwick Boseman on SNL Black Jeopardy",
    "upvote_ratio": 0.59,
    "url": "https://youtu.be/hzMzFGgmQOc?t=0"
  },
  {
    "id": "iiy8cd",
    "author": "Pornstar_Jesus_",
    "created_utc": 1598728181.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iiy8cd",
    "num_comments": 0,
    "over_18": false,
    "permalink": "/r/videos/comments/iiy8cd/the_rubberbandits_waiting/",
    "score": 2,
    "spoiler": false,
    "stickied": false,
    "title": "The Rubberbandits - Waiting",
    "upvote_ratio": 1.0,
    "url": "https://youtu.be/SAXGmyQGkHI"
  },
  {
    "id": "iip25z",
    "author": "skonats",
    "created_utc": 1598690001.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iip25z",
    "num_comments": 5,
    "over_18": false,
    "permalink": "/r/videos/comments/iip25z/the_disturbing_truth_about_mother_teresa_you/",
    "score": 14,
    "spoiler": false,
    "stickied": false,
    "title": "The Disturbing Truth About Mother Teresa You Never Knew",
    "upvote_ratio": 0.61,
    "url": "https://www.youtube.com/watch?v=jV4YzOwMu6I"
  },
  {
    "id": "iioq7x",
    "author": "xXxNOBELxXx",
    "created_utc": 1598687980.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iioq7x",
    "num_comments": 10,
    "over_18": false,
    "permalink": "/r/videos/comments/iioq7x/what_teenagers_looked_like_in_1991/",
    "score": 14,
    "spoiler": false,
    "stickied": false,
    "title": "What teenagers looked like in 1991!",
    "upvote_ratio": 0.69,
    "url": "https://www.youtube.com/watch?v=bGqtZUpJagA"
  },
  {
    "id": "iirufx",
    "author": "TenInchDong",
    "created_utc": 1598705384.0,
    "is_original_content": false,
    "link_flair_text": null,
    "locked": false,
    "name": "t3_iirufx",
    "num_comments": 1,
    "over_18": false,
    "permalink": "/r/videos/comments/iirufx/the_residents_one_minute_movies/",
    "score": 6,
    "spoiler": false,
    "stickied": false,
    "title": "The Residents - \"One Minute Movies\"",
    "upvote_ratio": 0.67,
    "url": "https://www.youtube.com/watch?v=MTJJb1UqjuA"
  }
];
